{{- if .Values.secrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  labels:
    {{- include "cost-management-redux.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  COST_CLIENT_ID: {{ .Values.secrets.costClientId | required "secrets.costClientId is required when secrets.create=true" | quote }}
  COST_CLIENT_SECRET: {{ .Values.secrets.costClientSecret | required "secrets.costClientSecret is required when secrets.create=true" | quote }}
{{- end }}
